name: Deploy to GCP

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY: 59vkckvlkjdfglkjdfv
  IMAGE_NAME: mandelbrot-tinker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        working-directory: ./deployment/gcp
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Apply Terraform
        working-directory: ./deployment/gcp
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform apply -auto-approve -var="image_tag=$(git describe --tags --abbrev=0)"