name: Go

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
              go-version: 1.23.5

        - name: Install dependencies
          run: go mod tidy

        - name: Run tests
          run: go test ./...

        - name: Check formatting
          run: gofmt -l .

        - name: Ensure no formatting changes
          run: |
            if [ -n "$(gofmt -l .)" ]; then
              echo "Code is not properly formatted. Please run 'gofmt'."
              exit 1
            fi